_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: '/home/user/models/step_gru_best_model.pt' 
  OUTPUT_DIM: 55
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_ALL.pt'

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/All_skills.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/All_skills.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/All_skills.csv"

OUTPUT:
  LOCATION: "/home/user/output"

SKILLS:
  - NAME: A8 - Nasopharyngeal Airway (NPA)
    STEPS:
    - Select NPA tube that best fits casualty.
    - Place casualty into 'sniffing position' with head tilted back and nostrils exposed.
    - Cover NPA with lube.
    - Insert NPA perpendicular to casualty nostril until flange meets tip of nose, rotating along the way.
    - Look, listen, and feel for airway compliance.      

  - NAME: M1 - Trauma Assessment
    STEPS:
    - Optionally unclothe depending on situation.
    - Sweep* left leg.
    - Sweep* right leg.
    - Sweep* left arm.
    - Sweep* right arm.
    - Look Listen Feel Breathing.
    - Rake** chest.
    - Roll over casualty.
    - Rake the back and buttocks.
    - Check pulse.
    - Check skin temperature/quality.
    - Expose and look at chest.
    - Optionally reclothe depending on situation.


  - NAME: M2 - Apply Tourniquet
    STEPS:
    - Place tourniquet over affected extremity 2-3 inches above wound site.
    - Pull tourniquet tight.
    - Apply strap to strap body.
    - Turn windless clock wise or counter clockwise until hemorrhage is controlled.
    - Lock windless into the windless keeper.
    - Pull remaining strap over the windless keeper.
    - Secure strap and windless keeper with keeper securing device.
    - Mark time on securing device strap with permanent marker.    


  - NAME: M3 - Apply pressure dressing
    STEPS:
    - Apply direct hand pressure.
    - Open dressing packaging.
    - Apply dressing with pressure point directly over wound site.
    - Wrap dressing around affected area extremity or trunk with 80 percent elastic stretch.
    - Secure dressing with securing device.

  - NAME: M4 - Wound Packing
    STEPS:
    - Apply direct hand pressure.
    - Open dressing packaging.
    - Pack wound.      

  - NAME: M5 - X-Stat
    STEPS:
    - Open inner packaging and remove applicator.
    - Insert applicator into wound track as close to bleeding source as possible.
    - Insert plunger into applicator.
    - Push plunger firmly to deploy sponges into wound.
    - Apply manual pressure if necessary.    

  - NAME: R16 - Ventilate (BVM)
    STEPS:
    - Place casualty into 'sniffing position' with head tilted back and nostrils exposed.
    - Open the BVM packaging.
    - Attach mask to BVM and expand BVM to full size.
    - Place mask over patient’s mouth in proper orientation.
    - Squeeze BVM while holding mask to patient’s mouth.   

  - NAME: R18 - Apply chest seal
    STEPS:
    - Cover and seal wound site with hands (apply pressure).
    - Open vented chest seal package.
    - Wipe blood and body fluids from wound site.
    - Peel away chest seal backer.
    - Place chest seal with circle of vents over wound site and seal to chest.

  - NAME: R19 - Needle Chest Decompression
    STEPS:
    - Locate insertion site at the second intercostal space at the midclavicular line.
    - Wipe the insertion site with an alcohol wipe.
    - Prepare catheter and needle.
    - Insert needle into insertion site and leave for 5-10 seconds.
    - Remove needle, keeping catheter inside the patient.
    - Apply tape around catheter to secure it in place.