_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: '/home/user/models/M1/step_gru_best_model.pt'
  OUTPUT_DIM: 13
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_M1.pt'  

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/M1_Alabama+BBN_videos.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/M1_Alabama+BBN_videos.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/M1_Alabama+BBN_videos.csv"

OUTPUT:
  LOCATION: "/home/user/output"

SKILLS:
  - NAME: M1 - Trauma Assessment
    STEPS:
      - Optionally unclothe depending on situation.
      - Sweep* left leg.
      - Sweep* right leg.
      - Sweep* left arm.
      - Sweep* right arm.
      - Look Listen Feel Breathing.
      - Rake** chest.
      - Roll over casualty.
      - Rake the back and buttocks.
      - Check pulse.
      - Check skin temperature/quality.
      - Expose and look at chest.
      - Optionally reclothe depending on situation.

## * Sweep means to run hands alongside body with slight pressure, periodically looking at your hands for new blood, trying to locate a source of bleeding on an extremity.
## ** Rake means to run fingers alongside body with pressure, feeling for holes or bumps, and looking for a reaction from the casualty to find an internal wound.