_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  
SKILLS:
  - NAME: M3 - Apply pressure dressing
    STEPS:
    - Apply direct hand pressure.
    - Open dressing packaging.
    - Apply dressing with pressure point directly over wound site.
    - Wrap dressing around effected area extremity or trunk with 80 precent elastic stretch.
    - Secure dressing with securing device.
    - Apply direct hand pressure for 5 minutes.
