MODEL:
  HIDDEN_SIZE: 1024
  CONTEXT_LENGTH: 'full'
##Milly  
#  OUTPUT_DIM: 42
#  SKILLS: ['pinwheels', 'coffee', 'mugcake']
#  DRIVE_ID: 1ArZFX4LuuB4SbmmWSDit4S8gPhkc2DRq
##BBN-Tourniquet
  OUTPUT_DIM: 9
  SKILLS: ['tourniquet']
  DRIVE_ID: 1ArZFX4LuuB4SbmmWSDit4S8gPhkc2DRq
##BBN-X-Stat
#  OUTPUT_DIM: 6 # offset 34
#  SKILLS: ['m5']
#  DRIVE_ID: 1SWl9ZZtX1xO6oSNFx5NueEbSP5K6IifE
##    
  USE_AUDIO: true
  USE_OBJECTS: true
  USE_BN: false
#  CHECKPOINT_FILE_PATH: "/scratch/ffd2011/procedural_step_recog/models/bbn_yolo_M5.pt"
  CHECKPOINT_FILE_PATH: "/scratch/ffd2011/data/BBN/tmp2/feature/omnimix/train/step_gru_best_model.pt"
DATASET:
  NAME: 'Milly'
  LOCATION: '/scratch/ffd2011/data/BBN/tmp/feature/omnivore'
  AUDIO_LOCATION: '/scratch/ffd2011/data/BBN/tmp/feature/slowfast/per-video'
  OBJECT_FRAME_LOCATION: '/scratch/ffd2011/data/BBN/tmp/feature/detic'
  VIDEO_LAYER: 'shoulders'
  #  TR_ANNOTATIONS_FILE: 'csv/BBN_train.csv'
  #  VL_ANNOTATIONS_FILE: 'csv/BBN_train.csv'
  TR_ANNOTATIONS_FILE: 'csv/train.csv'
  VL_ANNOTATIONS_FILE: 'csv/train.csv'
#  TS_ANNOTATIONS_FILE: 'csv/BBN_validation.csv'
  TS_ANNOTATIONS_FILE: 'csv/test.csv'
  INCLUDE_IMAGE_AUGMENTATIONS: False
  INCLUDE_TIME_AUGMENTATIONS: False
  FPS: 30
  HOP_SIZE: 0.5 # in seconds
DATALOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TRAIN:
  ENABLE: False
  NUM_GPUS: 1
  BATCH_SIZE: 1
  LR: 0.001
  EPOCHS: 5
OUTPUT:
  LOCATION: '/scratch/ffd2011/data/BBN/tmp2/feature/omnimix'  
