_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  OUTPUT_DIM: 5
  OMNIGRU_CHECKPOINT_URL: "/home/user/models/step_gru_best_model.pt"          

  CLASS: "OmniTransformer_v3"  #default class OmniGRU  

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/split/train.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/split/val.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/split/test.csv"   

  CLASS: 'Milly_multifeature_v6' #default Milly_multifeature_v4

OUTPUT:
  LOCATION: "/home/user/models/test"

TRAIN:
  ENABLE: False         #default: True
  SPLIT_10P_TEST: False #default: True

SKILLS:
  - NAME: A8 - Nasopharyngeal Airway (NPA)
    STEPS:
      - Select NPA tube that best fits casualty.
      - Place casualty into 'sniffing position' with head tilted back and nostrils exposed.
      - Cover NPA with lube.
      - Insert NPA perpendicular to casualty nostril until flange meets tip of nose, rotating along the way.
      - Look, listen, and feel for airway compliance.      
