_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  OUTPUT_DIM: 5
  YOLO_CHECKPOINT_URL: '/scratch/ffd2011/procedural_step_recog/models/yolo_downloaded_06142024/bbn_yolo_A8.pt'  
  OMNIGRU_CHECKPOINT_URL: "/scratch/ffd2011/data/BBN/new/A8/output/december_demo/transformer_original_scheduler/aug_img_perc0.8/step_gru_best_model.pt"          

  CLASS: 'OmniTransformer_v3'  #default class OmniGRU

DATASET:
  TS_ANNOTATIONS_FILE: "/scratch/ffd2011/data/BBN/new/A8/labels/A8_Alabama+BBN_videos.csv" #test ONLY with these videos 

TRAIN:
  ENABLE: False         #default: True
  SPLIT_10P_TEST: False #default: True

SKILLS:
  - NAME: A8 - Nasopharyngeal Airway (NPA)
    STEPS:
      - Select NPA tube that best fits casualty.
      - Place casualty into 'sniffing position' with head tilted back and nostrils exposed.
      - Cover NPA with lube.
      - Insert NPA perpendicular to casualty nostril until flange meets tip of nose, rotating along the way.
      - Look, listen, and feel for airway compliance.      
