_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  OUTPUT_DIM: 5
  YOLO_CHECKPOINT_URL: '/scratch/ffd2011/procedural_step_recog/models/yolo_downloaded_06142024/bbn_yolo_A8.pt'  

  CLASS: 'OmniGRU'  #default class OmniGRU

DATASET:
  TR_ANNOTATIONS_FILE: "/scratch/ffd2011/data/BBN/new/A8/labels/A8_Alabama+BBN_videos.csv"  #run cross-validation over the same videos
  VL_ANNOTATIONS_FILE: "/scratch/ffd2011/data/BBN/new/A8/labels/A8_Alabama+BBN_videos.csv"  #run cross-validation over the same videos
  TS_ANNOTATIONS_FILE: "/scratch/ffd2011/data/BBN/new/A8/labels/A8_Alabama+BBN_videos.csv"  #extract 10% of the videos for testing (SPLIT_10P_TEST: True)

OUTPUT:
  LOCATION: "/scratch/ffd2011/data/BBN/new/A8/output/december_demo/test"

TRAIN:
  ENABLE: True               #default: True
  USE_CROSS_VALIDATION: True #default: True
  SPLIT_10P_TEST: True       #default: False 

SKILLS:
  - NAME: A8 - Nasopharyngeal Airway (NPA)
    STEPS:
      - Select NPA tube that best fits casualty.
      - Place casualty into 'sniffing position' with head tilted back and nostrils exposed.
      - Cover NPA with lube.
      - Insert NPA perpendicular to casualty nostril until flange meets tip of nose, rotating along the way.
      - Look, listen, and feel for airway compliance.      
