_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  OUTPUT_DIM: 5
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_A8.pt'  

  CLASS: 'OmniTransformer_v3'  #default class OmniGRU

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/A8_Alabama+BBN_videos.csv"  #run cross-validation over the same videos
  VL_ANNOTATIONS_FILE: "/home/user/labels/A8_Alabama+BBN_videos.csv"  #run cross-validation over the same videos
  TS_ANNOTATIONS_FILE: "/home/user/labels/A8_Alabama+BBN_videos.csv"  #extract 10% of the videos for testing (SPLIT_10P_TEST: True)

  CLASS: 'Milly_multifeature_v6' #default Milly_multifeature_v4

OUTPUT:
  LOCATION: "/home/user/output"

TRAIN:
  ENABLE: True               #default: True
  USE_CROSS_VALIDATION: True #default: True
  SPLIT_10P_TEST: True       #default: False 

  BATCH_SIZE: 8      #default 32
  OPT: "adamw"       #default adam
  LR: 0.0001         #default 0.001
  WEIGHT_DECAY: 0.05 #default 0.0
  SCHEDULER: 'cos'   #default None
  EPOCHS: 30         #default 5

SKILLS:
  - NAME: A8 - Nasopharyngeal Airway (NPA)
    STEPS:
      - Select NPA tube that best fits casualty.
      - Place casualty into 'sniffing position' with head tilted back and nostrils exposed.
      - Cover NPA with lube.
      - Insert NPA perpendicular to casualty nostril until flange meets tip of nose, rotating along the way.
      - Look, listen, and feel for airway compliance.      
